### PR TITLE
Fix wrong required validation even when field value was typed

### PR DESCRIPTION
**Pull request by marcellustavares**
hey @igorarouca @dylan-rebelak,

this is the data provider applied to the text field, you should find an option on the text configuration "attach data provider" with this pull.

Regards,

### CODE REVIEW

**Comment by igorarouca** [comment]
Hey @marcellustavares, let us know when you have time to discuss this PR. Dylan and I already tested it today. Thanks

**Comment by igorarouca** [comment]
By the way, there's a minor typo on:
dynamic-data-mapping-type-text/src/main/resources/META-INF/resources/text_field.js

I believe @fernandosouza meant _getAutoCompleteData instead of _getAutoCompateData

**Comment by marcellustavares** [comment]
thx @igorarouca :)

**Comment by igorarouca** [comment]
Merged to #boa branch

**Pull request closed without merging**
